addpath( ...
    '/Users/Juraj/Documents/Optimization/matpower/lib', ...
    '/Users/Juraj/Documents/Optimization/matpower/lib/t', ...
    '/Users/Juraj/Documents/Optimization/matpower/data', ...
    '/Users/Juraj/Documents/Optimization/matpower/mips/lib', ...
    '/Users/Juraj/Documents/Optimization/matpower/mips/lib/t', ...
    '/Users/Juraj/Documents/Optimization/matpower/most/lib', ...
    '/Users/Juraj/Documents/Optimization/matpower/most/lib/t', ...
    '/Users/Juraj/Documents/Optimization/matpower/mptest/lib', ...
    '/Users/Juraj/Documents/Optimization/matpower/mptest/lib/t', ...
    '-end' );

prefix = 'case118';
mpc = case118;

%load bus 'locations'
case118Layout;

% create line properties to visualize
LineVarsLabelsi = {'rateA' 'R'};
LineVars = [mpc.branch(:,6) mpc.branch(:,3)];

% create bus properties to visualize
BusVarsLabels = {'type', 'PD'};
BusVars =  [ mpc.bus(:,2) mpc.bus(:,3)];

visualizePowerGrid(prefix, mpc, locations, LineVars, LineVarsLabelsi, BusVars, BusVarsLabels )