clc
close all

addpath( ...
    '/Users/Juraj/Documents/Optimization/matpower/lib', ...
    '/Users/Juraj/Documents/Optimization/matpower/lib/t', ...
    '/Users/Juraj/Documents/Optimization/matpower/data', ...
    '/Users/Juraj/Documents/Optimization/matpower/mips/lib', ...
    '/Users/Juraj/Documents/Optimization/matpower/mips/lib/t', ...
    '/Users/Juraj/Documents/Optimization/matpower/most/lib', ...
    '/Users/Juraj/Documents/Optimization/matpower/most/lib/t', ...
    '/Users/Juraj/Documents/Optimization/matpower/mptest/lib', ...
    '/Users/Juraj/Documents/Optimization/matpower/mptest/lib/t', ...
    '-end' );

addpath( ...
    '/Users/Juraj/Documents/Optimization/matpower/lib/mpopf', ...
    '/Users/Juraj/Documents/Optimization/matpower/lib/mpopf/ticinoData', ...
    '-end' );

setenv('OMP_NUM_THREADS', '1')

warning('off','all');

define_constants;
%% create case
mpc = case1354pegase;

% mpc fixes as done by Alex
mpc = ext2int(mpc); mpc = rmfield(mpc,'order');
mpc.branch(mpc.branch(:,RATE_A)==0,RATE_A) = 9900;
mpc.gen(:,PMIN) = 0;

%% initialization mode
%  1 = default starting point
%  2 = starting point taken directly from mpc
%  3 = AC power flow solution used as starting point
init_mode = 1;

mpopt = mpoption('verbose', 2, 'out.all', 1);
mpopt = mpoption(mpopt, 'opf.start', init_mode);

%% load scaling profile for the time horizon
profile = createLoadProfile();
profile = scaleLoadProfile(profile, mpc, 0, 0);

%% prepare the storages
Rfirst = 0.00; %% relative position of the storage placement when sorted by PD from largest first
Rcount = 0.02; %% fraction of the PD buses that will have storage
Emax = 2; %% max capacity of the storage relative to a PD at given bus
    
storage_param = createStorage(mpc, Rfirst, Rcount, Emax);

T_timestep_hours = 1;
mpc_storage = add_storage2bNoPeriodic(mpc,size(mpc.bus,1),length(profile), ...
                                      storage_param.id_storage_location, ...
                                      storage_param.P_storage_max_MW,...
                                      storage_param.P_storage_min_MW,...
                                      storage_param.E_storage_max_MWh,...
                                      storage_param.E_storage_init_MWh,...
                                      storage_param.c_discharge,...
                                      storage_param.c_charge, ...
                                      T_timestep_hours);                                 
%%
runmpopf(mpc_storage, profile, mpopt);